Updated the logic so that we don't throw an internal server error if …
companieshouse/accounts-user-api pull request #10
Opened 2024-02-13 15:51 UTC by krishna-patel-ch

__Short description outlining key changes/additions__

Updated the logic so that we don't throw an internal server error if the record was not updated

__JIRA Ticket Number__

IDVA6-509

### Type of change

* [ ] Bug fix
* [ ] New feature
* [ ] Breaking change
* [ ] Infrastructure change

### Pull request checklist

* [ ] I have added unit tests for new code that I have added
* [ ] I have added/updated functional tests where appropriate
* [ ] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)

__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

2024-02-13 16:00 UTC, kkonuganti-ch requested changes

2024-02-13 16:00 UTC, kkonuganti-ch commented on src/test/java/uk/gov/companieshouse/accounts/user/integration/UsersServiceTest.java
> +        usersService.setRoles( null, List.of( Role.SUPPORT_MEMBER ) );
wrong test, ids should be mandatory and it should still throw error if not found. 404.

2024-02-13 16:00 UTC, kkonuganti-ch commented on src/test/java/uk/gov/companieshouse/accounts/user/service/UsersServiceTest.java
> +        usersService.setRoles( null, List.of( Role.SUPPORT_MEMBER ) );
do not set roles for user null, thats wrong.

2024-02-13 17:03 UTC, ch-code-analysis commented
CI: No security warnings found

2024-02-14 08:59 UTC, kkonuganti-ch approved these changes

2024-02-14 08:59 UTC, merged