Feature/cc 1306
companieshouse/accounts-user-api pull request #28
Opened 2024-04-09 15:39 UTC by dtoulcher-ch

__Short description outlining key changes/additions__

__JIRA Ticket Number__

### Type of change

* [ ] Bug fix
* [ ] New feature
* [ ] Breaking change
* [ ] Infrastructure change

### Pull request checklist

* [ ] I have added unit tests for new code that I have added
* [ ] I have added/updated functional tests where appropriate
* [ ] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)

__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

2024-04-09 15:43 UTC, ch-code-analysis commented
CI: No security warnings found

2024-04-09 15:51 UTC, NeilShadrach commented on src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java
> +                .addPathPatterns("/**")
Make this a constant? I think sonar complains if it sees repeated strings

2024-04-10 07:50 UTC, bcullerton requested changes

2024-04-10 07:50 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java
> +
Extra whitespace here

2024-04-10 07:50 UTC, bcullerton commented on src/main/resources/application.properties
> +management.endpoints.web.path-mapping.health=/account-user-api/healthcheck
This would change the existing healthcheck path. Assuming Inugami are happy it'll need changing in the terraform as well for the healthcheck shell call.

Also path should probably match the repo /accounts-user-api

2024-04-10 07:50 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/accounts/user/interceptor/PrivilegesInterceptor.java
> +    private final static List<String> OAUTH_IDENTITY_TYPE = Collections.singletonList("oauth2");
I don't think we want to add oauth2 as an allowed identity-type for our endpoint.

2024-04-10 07:50 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/accounts/user/interceptor/PrivilegesInterceptor.java
> +public class PrivilegesInterceptor extends UserAuthenticationInterceptor {
I don't think we need to make changes to this class. I'd just hide our endpoints behind the InternalUserInterceptor in config and leave the inugami endpoints behind the existing EricAuthorisedKeyPrivilegesInterceptor. Separate Interceptors seems appropriate here.

2024-04-15 14:50 UTC, dtoulcher-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/interceptor/PrivilegesInterceptor.java
> +public class PrivilegesInterceptor extends UserAuthenticationInterceptor {
Added the new Interceptor into api-security-java after the meeting last week.

2024-04-15 14:50 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-15 14:59 UTC, dtoulcher-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java
> +                .addPathPatterns("/**")
Fair point it probably will, I've updated.

2024-04-15 15:01 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-16 09:03 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java
> +    private void addInternlUserAdminSearchInterceptor( final InterceptorRegistry registry){
Should search be in this function name? Won't always cover search endpoints

2024-04-16 09:29 UTC, kkonuganti-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java
>          addEricInterceptors(registry);
add eric interceptors, users internal user interceptors, which already checks for oauth2. 

Should we not amend out current interceptor to not check for oauth2 and then use the new interceptor to check for oauth2. In this way eric interceptor we are using can only check for api keys.
may be change the type of intercertor we are using to only apikey? happy to get on a call.

2024-04-16 09:30 UTC, dtoulcher-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java
> +    private void addInternlUserAdminSearchInterceptor( final InterceptorRegistry registry){
The way I see it, we'll need to add new Interceptor configs per each endpoint as they'll have different role permissions.

2024-04-16 10:01 UTC, bcullerton commented on src/main/java/uk/gov/companieshouse/accounts/user/configuration/InterceptorConfig.java
>          addEricInterceptors(registry);
We're checking for a different type of permission to the standard oauth2 checks. For most user journeys the authorisation property you want to check is token_permissions. In our case we're checking a permissions property instead which eric populates into a different header. There's a good chance you won't be able to use our interceptor unless you're validating someone has admin permissions.

2024-04-16 13:49 UTC, dtoulcher-ch commented on src/main/resources/application.properties
> +management.endpoints.enabled-by-default=false
That is true, but I like to make it clear what the default behavor is for the endpoints.

2024-04-16 15:30 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-16 15:39 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-17 10:09 UTC, bcullerton approved these changes

2024-04-17 10:13 UTC, kkonuganti-ch submitted a review, later dismissed

2024-04-17 16:59 UTC, bcullerton approved these changes

2024-04-17 17:02 UTC, ch-code-analysis commented
CI: Security warnings found!

2024-04-17 17:15 UTC, merged