Idva6 509 put user roles
companieshouse/accounts-user-api pull request #7
Opened 2024-02-09 10:46 UTC by krishna-patel-ch

__Short description outlining key changes/additions__

New endpoint for updating a user's roles.

__JIRA Ticket Number__

IDVA6 509

### Type of change

* [ ] Bug fix
* [x] New feature
* [ ] Breaking change
* [ ] Infrastructure change

### Pull request checklist

* [x] I have added unit tests for new code that I have added
* [x] I have added/updated functional tests where appropriate
* [x] The code follows our [coding standards](https://github.com/companieshouse/styleguides/blob/master/java.md)

__An exhaustive list of peer review checks can be read [here](https://github.com/companieshouse/styleguides/blob/master/java_review.md#developer-actions-prior-to-code-commitreview-started)__

2024-02-09 12:20 UTC, kkonuganti-ch requested changes

2024-02-09 12:20 UTC, kkonuganti-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/controller/UserRolesController.java
> +        usersService.setRoles( userId, roles );
how are you checking if the roles are actually updated?

2024-02-09 12:20 UTC, kkonuganti-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/repositories/UsersRepository.java
> +    void updateUser( String userId, Update update );
probably return the object here once updated. update user should return an object using repo.
then user assert that in service to see if the status is updated.

2024-02-09 12:20 UTC, kkonuganti-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/service/UsersService.java
>      public List<User> fetchUsers( final List<String> emails ) {
you should be able to add @transactional at class level. 
Method level could be used if you are propagating something else. e.g. Trasactional(propogation.NEW) will always.create a new transaction session everytime an update happens.

2024-02-09 12:48 UTC, ch-code-analysis commented
CI: No security warnings found

2024-02-09 12:51 UTC, krishna-patel-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/controller/UserRolesController.java
> +        usersService.setRoles( userId, roles );
The if statement on line 61 will verify that the user exists in the database, if not then the method returns 404 not found. This means by the time we reach line 66, we can guarantee that the user exists.

The setRoles method is guaranteed to update the user's roles (as long as the user actually exists, which we know is the case by this point in the code).

I guess, if something weird happens like the database connection failed and it couldn't update, it would crash and return a 500, so you wouldn't get the 201 Created response in that case.

Ran comprehensive set of tests that confirm that the update is performed correctly.

2024-02-09 13:47 UTC, kkonuganti-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/controller/UserRolesController.java
> +        usersService.setRoles( userId, roles );
if something happened and it did not commit @transactionsl will handle that. That will make sure the db transaction is either committed or rolled back.
hence if we can check in service to return after update and assert, that would be good.

2024-02-09 15:44 UTC, krishna-patel-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/service/UsersService.java
>      public List<User> fetchUsers( final List<String> emails ) {
Done

2024-02-09 16:04 UTC, ch-code-analysis commented
CI: No security warnings found

2024-02-12 09:48 UTC, kkonuganti-ch approved these changes
LGTM

2024-02-12 09:48 UTC, kkonuganti-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/repositories/UsersRepository.java
> +    int updateUser( String userId, Update update );
what if it updates 2 records?

2024-02-12 09:58 UTC, krishna-patel-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/controller/ControllerAdvice.java
> +        contextMap.put("query-parameters", request.getQueryString() != null ? "?" + request.getQueryString() : "");
This is just used for logging, to make it easier to debug errors, so it should be fine

2024-02-12 10:20 UTC, krishna-patel-ch commented on src/main/java/uk/gov/companieshouse/accounts/user/repositories/UsersRepository.java
> +    int updateUser( String userId, Update update );
The int is the number of documents updated. So if one document is updated, the output will be 1 and if two documents are updated, the output will be 2 etc.

2024-02-12 12:03 UTC, merged